### ISSUE TITLE
[Main] Naver 검색창 구현

### ISSUE THREAD

**Issue by zooragi** [zooragi/NaverMainPage#3]
## Main Page
   * 검색창 기능 구현

## Tasks
- [x] 검색했을 때, 검색어 저장(배열 -> localStorage -> Server ) 기능 구현
- [x] 최근 검색창 UI 만들기
- [x] 최근 검색창 기능 구현( 추가만 하였음 )
- [x]  검색창이 포커싱 되었을 때 최근 검색어 보여주는 기능 구현
- [ ] 최근 검색창 리스트 전체 삭제 및 부분 삭제 기능 구현
- [ ] 저장한 검색어 버튼 클릭시 list로 보여주는 기능 구현
